### Cadastrar Aluno
POST http://localhost:5000/api/aluno/cadastrar
Content-Type: application/json

{
  "nome": "Vitor Marques"
}

### Cadastrar IMC
POST http://localhost:5000/api/imc/cadastrar
Content-Type: application/json

{
  "alunoId": 1,
  "peso": 100,
  "altura": 1.85
}

### Listar IMCs
GET http://localhost:5000/api/imc/listar

### Listar IMCs por Aluno
GET http://localhost:5000/api/imc/listarporaluno/1

### Alterar IMC
PUT http://localhost:5000/api/imc/alterar/1
Content-Type: application/json

{
  "peso": 80,
  "altura": 1.80
}
